repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
        log_file: logs/pre-commit.log

      - id: end-of-file-fixer
        log_file: logs/pre-commit.log

      - id: trailing-whitespace
        log_file: logs/pre-commit.log

      - id: check-json
        log_file: logs/pre-commit.log

      - id: check-ast
      - id: check-toml

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
      - id: add-trailing-comma

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=.pylintrc", # Link to your config file
          ]
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        args: ["--check", --config=pyproject.toml]

      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]

      - id: mypy
        name: Validate types with MyPy
        entry: poetry run mypy --config-file pyproject.toml .
        language: system
        types: [python]
        pass_filenames: false
