name: Build Project
description: "Shared Steps Between Workflows"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    #----------------------------------------------
    #           install & configure uv
    #----------------------------------------------
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    #----------------------------------------------
    #       install dependencies with uv
    #----------------------------------------------
    - name: Install dependencies
      shell: bash
      run: |
        uv sync
