name: Code Validation

on:
  pull_request:
    branches:
      - main

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python and uv
        uses: ./.github/workflows/actions/setup-composite
      - name: Install and run ruff
        run: |
          files=$(git diff --diff-filter=d --name-only origin/${{ github.base_ref }}..HEAD | grep "\.py$" | grep -vE "config|examples|fabfile|manage.py|migrations|venv|build" | tr '\n' ' ' || true)
          if [ -n "$files" ];then uv sync --group ruff;else exit 0; fi
          uv run --group ruff ruff format --check $files
          uv run --group ruff ruff check $files
  mypy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python and uv
        uses: ./.github/workflows/actions/setup-composite
      - name: Install and run mypy
        run: |
          changed_python_files=$(git diff --diff-filter=d --name-only origin/${{ github.base_ref }}..HEAD | grep "\.py$" | grep -vE "config|examples|fabfile|manage.py|migrations|venv|build" | tr '\n' ' ' || true)
          if [ -n "$changed_python_files" ];then uv sync --group mypy;else exit 0; fi
          uv run --group mypy mypy .
