name: Code Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  black-check:
    env:
      TARGET_COMMIT: ${{ github.base_ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/setup-composite
      - name: Install and run black
        run: |
          files=$(git diff --diff-filter=d --name-only origin/$TARGET_COMMIT..HEAD | grep "\.py$" | grep -vE "config|examples|fabfile|manage.py|migrations|venv|build" | tr '\n' ' ' || true)
          if [ -n "$files" ];then poetry install --only black;else exit 0; fi
          black --check -v --config ${{ github.workspace }}/pyproject.toml $files
  isort-check:
    env:
      TARGET_COMMIT: ${{ github.base_ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/setup-composite
      - name: Install and run isort
        run: |
          files=$(git diff --diff-filter=d --name-only origin/$TARGET_COMMIT..HEAD | grep "\.py$" | grep -vE "config|examples|fabfile|manage.py|migrations|venv|build" | tr '\n' ' ' || true)
          if [ -n "$files" ];then poetry install --only isort;else exit 0; fi
          isort -v --check --profile black --settings-path ${{ github.workspace }}/pyproject.toml --atomic $files
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/setup-composite
      - name: Install poetry and pylint and run pylint
        run: |
          changed_python_files=$(git diff --diff-filter=d --name-only origin/$TARGET_COMMIT..HEAD | grep "\.py$" | grep -vE "config|examples|fabfile|manage.py|migrations|venv|build" | tr '\n' ' ' || true)
          if [ -n "$changed_python_files" ];then poetry install --only pylint;else exit 0; fi
          poetry run pylint --count .
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/setup-composite
      - name: Install poetry and mypy and run mypy
        run: |
          changed_python_files=$(git diff --diff-filter=d --name-only origin/$TARGET_COMMIT..HEAD | grep "\.py$" | grep -vE "config|examples|fabfile|manage.py|migrations|venv|build" | tr '\n' ' ' || true)
          if [ -n "$changed_python_files" ];then poetry install --only mypy;else exit 0; fi
          poetry run mypy .
